### ISSUE TITLE
Got arguments error with demo code and decompress with javascript lz-string

### ISSUE THREAD

**Issue by shezhangzhang** [adumbidiot/lz-str-rs#18]
<img width="906" alt="image" src="https://user-images.githubusercontent.com/26793777/195561967-203089ec-ce1e-460e-9f73-601ede85c0dc.png">

**Comment by adumbidiot** [comment]
Yeah I’m pretty I wrote that demo during the first few iterations of this library. I’d look into `compress_str` for now, but I’ll try to write up a better example in the next few days.

**Comment by shezhangzhang** [comment]
Could you apply to add a rust solution link here? [lz-string repo readme](https://github.com/pieroxy/lz-string/#other-languages)

**Comment by adumbidiot** [comment]
Oops, I misclicked. Thanks for submitting that pull request. I’ll leave adding this repo to that read me to you since you already have a PR open.

**Comment by shezhangzhang** [comment]
Thanks for your great work!

**Comment by shezhangzhang** [comment]
@adumbidiot Sorry, I'm a new to Rust language, I have a problem, could you help me out ? Thanks!
![image](https://user-images.githubusercontent.com/26793777/195888178-842a941c-aeee-4662-a16d-c6cbf49703fa.png)
<img width="770" alt="image" src="https://user-images.githubusercontent.com/26793777/195888229-32752972-a4a9-4bb0-8922-738a0595742e.png">
here is the body looks like: original body======: b"\xe3\x9e\x82\xe2\x82\xb6\xe0\xa9\xa0\xec\xb9\x90\xe8\x98\x8e\xe6\x84\x90\xe0\xae\x84\xd9\x90\xe3\xb6\xa4.......

How do I solve this? decompress_str(???);

**Comment by adumbidiot** [comment]
Oops, I forgot that the version on crates.io has a weird interface. The master branch of this repository should have a nicer one. I'll publish a new version after I update the example. You can see the docs for the master branch [here](https://adumbidiot.github.io/lz-str-rs/lz_str/). [This page](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html) should help with specifying git dependencies. 

This library (on master at least) assumes that inputs and outputs are possibly invalid utf16 strings. I'll need to think a bit how to handle decompression from raw bytes. I'll get back to you on that after I fix the example. As a side note, you are getting this bytes object through the reqwest right?

One problem I see is that you are trying to create a Future by hand. This is almost definitely something that you don't want to do, especially as a beginner. I would suggest looking into async functions, which is how futures are intended to be used most of the time. Look at [this](https://github.com/seanmonstar/reqwest/blob/master/examples/simple.rs) for a basic example. You can replace text with bytes.

**Comment by shezhangzhang** [comment]
Yes, I am getting this bytes from the request(Rust Actix web), this bytes maybe handle with the framework. The request body shows it's a "Bytes".
This request from my own frontend. I used the javascript lz-string(compress) to compress the body. 
And my point is: decompress the body in rust web server.

**Comment by adumbidiot** [comment]
Ah I see. I thought you were using [reqwest, the http client](https://docs.rs/reqwest/latest/reqwest/index.html). 

I've updated the examples on the readme and the documentation. I have a few things I want to do before making a new release though.

Assuming you are on the master branch, if you compress with `LZString.compress` on the frontend, you need to decompress with `lz_str::decompress`. However, this function expects a wide string. I could add a way for this library convert from a byte array to a wide string automatically, but I'm not sure if I like that solution. I will think about that for a bit.

To solve the problem on your side, you want to transform a byte slice, `&[u8]` into a `Vec<u16>`, so that this decompression library can understand that. I'll write up an example for that quickly.

**Comment by adumbidiot** [comment]
Alright, I've added https://github.com/adumbidiot/lz-str-rs/blob/master/examples/binary-data.rs. Let me know if you have any issues with it.

**Comment by adumbidiot** [comment]
Actually, would it be possible for you to use `compressToUint8Array` on your frontend? This sounds like what that function is designed for.

**Comment by shezhangzhang** [comment]
> Actually, would it be possible for you to use `compressToUint8Array` on your frontend? This sounds like what that function is designed for.

OK, you mean `compressToUint8Array()` is better than `compress` if I want to get less http transfer size in this case? I'll try it now! Thanks a lot!!!

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/26793777/195985228-f55d3efb-f914-431e-925b-0d22079d1ded.png">

**Comment by adumbidiot** [comment]
compressToUint8Array should create a string that is the same size as one made with compress. I suggested using it here because it's difficult to send invalid strings across the network, like the one you would get with compress. Treating the output as a  byte array instead of a string makes it easier to deal with.

**Comment by shezhangzhang** [comment]
Thanks! I'll checkout to prod version after you release the latest version on create.io.

**Comment by shezhangzhang** [comment]
Very appreciate for your great job! Thanks again :D 💯 👍  @adumbidiot

**Comment by adumbidiot** [comment]
Version 0.2.0 of this library has now been released. Let me know if you run into any more issues.

**Comment by shezhangzhang** [comment]
Great job！👍
